"""
Agent Response model for the RAG Agent API
"""
from typing import List, Dict, Optional
from pydantic import BaseModel
from .retrieved_context import SourceCitation


class AgentResponse(BaseModel):
    """
    The answer generated by the AI Agent, grounded in retrieved context with citations
    """
    answer: str
    citations: List[SourceCitation]
    grounded: bool
    retrieved_context: Optional[List[Dict]] = None  # The context that was used to generate the response
    execution_time_ms: float
    confidence_score: Optional[float] = None  # Confidence in the response accuracy